--PLACES
ALTER TABLE CONTINENT ADD DATE_CREATION DATE;
ALTER TABLE CONTINENT ADD USER_CREATION VARCHAR2(30);
ALTER TABLE CONTINENT ADD DATE_MODIFICATION DATE;
ALTER TABLE CONTINENT ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE COUNTRY ADD DATE_CREATION DATE;
ALTER TABLE COUNTRY ADD USER_CREATION VARCHAR2(30);
ALTER TABLE COUNTRY ADD DATE_MODIFICATION DATE;
ALTER TABLE COUNTRY ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE PROVINCE ADD DATE_CREATION DATE;
ALTER TABLE PROVINCE ADD USER_CREATION VARCHAR2(30);
ALTER TABLE PROVINCE ADD DATE_MODIFICATION DATE;
ALTER TABLE PROVINCE ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE CANTON ADD DATE_CREATION DATE;
ALTER TABLE CANTON ADD USER_CREATION VARCHAR2(30);
ALTER TABLE CANTON ADD DATE_MODIFICATION DATE;
ALTER TABLE CANTON ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE DISTRICT ADD DATE_CREATION DATE;
ALTER TABLE DISTRICT ADD USER_CREATION VARCHAR2(30);
ALTER TABLE DISTRICT ADD DATE_MODIFICATION DATE;
ALTER TABLE DISTRICT ADD USER_MODIFICATION VARCHAR2(30);


--ANIMALS
ALTER TABLE ANML_CLASS ADD DATE_CREATION DATE;
ALTER TABLE ANML_CLASS ADD USER_CREATION VARCHAR2(30);
ALTER TABLE ANML_CLASS ADD DATE_MODIFICATION DATE;
ALTER TABLE ANML_CLASS ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE ANML_FAMILY ADD DATE_CREATION DATE;
ALTER TABLE ANML_FAMILY ADD USER_CREATION VARCHAR2(30);
ALTER TABLE ANML_FAMILY ADD DATE_MODIFICATION DATE;
ALTER TABLE ANML_FAMILY ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE ANML_GENDER ADD DATE_CREATION DATE;
ALTER TABLE ANML_GENDER ADD USER_CREATION VARCHAR2(30);
ALTER TABLE ANML_GENDER ADD DATE_MODIFICATION DATE;
ALTER TABLE ANML_GENDER ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE ANML_ORDER ADD DATE_CREATION DATE;
ALTER TABLE ANML_ORDER ADD USER_CREATION VARCHAR2(30);
ALTER TABLE ANML_ORDER ADD DATE_MODIFICATION DATE;
ALTER TABLE ANML_ORDER ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE ANML_SUBORDER ADD DATE_CREATION DATE;
ALTER TABLE ANML_SUBORDER ADD USER_CREATION VARCHAR2(30);
ALTER TABLE ANML_SUBORDER ADD DATE_MODIFICATION DATE;
ALTER TABLE ANML_SUBORDER ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE ANML_SPECIE ADD DATE_CREATION DATE;
ALTER TABLE ANML_SPECIE ADD USER_CREATION VARCHAR2(30);
ALTER TABLE ANML_SPECIE ADD DATE_MODIFICATION DATE;
ALTER TABLE ANML_SPECIE ADD USER_MODIFICATION VARCHAR2(30);

--OTHERS
ALTER TABLE SYSTEM_USER ADD DATE_CREATION DATE;
ALTER TABLE SYSTEM_USER ADD USER_CREATION VARCHAR2(30);
ALTER TABLE SYSTEM_USER ADD DATE_MODIFICATION DATE;
ALTER TABLE SYSTEM_USER ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE SYSTEM_PARAMETERS ADD DATE_CREATION DATE;
ALTER TABLE SYSTEM_PARAMETERS ADD USER_CREATION VARCHAR2(30);
ALTER TABLE SYSTEM_PARAMETERS ADD DATE_MODIFICATION DATE;
ALTER TABLE SYSTEM_PARAMETERS ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE BINNACLE ADD DATE_CREATION DATE;
ALTER TABLE BINNACLE ADD USER_CREATION VARCHAR2(30);
ALTER TABLE BINNACLE ADD DATE_MODIFICATION DATE;
ALTER TABLE BINNACLE ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE IMAGE ADD DATE_CREATION DATE;
ALTER TABLE IMAGE ADD USER_CREATION VARCHAR2(30);
ALTER TABLE IMAGE ADD DATE_MODIFICATION DATE;
ALTER TABLE IMAGE ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE SIGHT ADD DATE_CREATION DATE;
ALTER TABLE SIGHT ADD USER_CREATION VARCHAR2(30);
ALTER TABLE SIGHT ADD DATE_MODIFICATION DATE;
ALTER TABLE SIGHT ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE RATEXUSER ADD DATE_CREATION DATE;
ALTER TABLE RATEXUSER ADD USER_CREATION VARCHAR2(30);
ALTER TABLE RATEXUSER ADD DATE_MODIFICATION DATE;
ALTER TABLE RATEXUSER ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE ORNITHOLOGIST ADD DATE_CREATION DATE;
ALTER TABLE ORNITHOLOGIST ADD USER_CREATION VARCHAR2(30);
ALTER TABLE ORNITHOLOGIST ADD DATE_MODIFICATION DATE;
ALTER TABLE ORNITHOLOGIST ADD USER_MODIFICATION VARCHAR2(30);

ALTER TABLE AMATEUR ADD DATE_CREATION DATE;
ALTER TABLE AMATEUR ADD USER_CREATION VARCHAR2(30);
ALTER TABLE AMATEUR ADD DATE_MODIFICATION DATE;
ALTER TABLE AMATEUR ADD USER_MODIFICATION VARCHAR2(30);