--                              ***************************************
--                                  INSERT PROVINCES FROM COSTA RICA
--                              ***************************************
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 1, 'San Jose');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 2, 'Alajuela');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 3, 'Cartago');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 4, 'Heredia');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 5, 'Guanacaste');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 6, 'Puntarenas');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 7, 'Limon');

CREATE SEQUENCE SEQ_DISTRICT
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE
ORDER;




--                                      ************************
--                                      |       SAN JOSE       |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,101,'SAN JOSE');
--DISTRITOS SAN JOSE / SAN JOSE--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'CARMEN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'MERCED');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'HOSPITAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'CATEDRAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'ZAPOTE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'SAN FRANCISCO DE DOS RIOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'URUCA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'MATA REDONDA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'PAVAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'HATILLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(101,SEQ_DISTRICT.NEXTVAL,'SAN SEBASTIAN');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,102,'ESCAZU');
--DISTRITOS SAN JOSE / ESCAZU--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(102,SEQ_DISTRICT.NEXTVAL,'ESCAZU');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(102,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(102,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,103,'DESAMPARADOS');
--DISTRITOS SAN JOSE / DESAMPARADOS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'DESAMPARADOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN MIGUEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN JUAN DE DIOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL ARRIBA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'FRAILES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'PATARRA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN CRISTOBAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'ROSARIO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'DAMAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL ABAJO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(103,SEQ_DISTRICT.NEXTVAL,'GRAVILIAS');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,104,'PURISCAL');
--DISTRITOS SAN JOSE / PURISCAL--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(104,SEQ_DISTRICT.NEXTVAL,'SANTIAGO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(104,SEQ_DISTRICT.NEXTVAL,'MERCEDES SUR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(104,SEQ_DISTRICT.NEXTVAL,'BARBACOAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(104,SEQ_DISTRICT.NEXTVAL,'GRIFO ALTO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(104,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(104,SEQ_DISTRICT.NEXTVAL,'CANDELARIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(104,SEQ_DISTRICT.NEXTVAL,'DESAMPARADITOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(104,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(104,SEQ_DISTRICT.NEXTVAL,'CHIRES');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,105,'TARRAZU');
--DISTRITOS SAN JOSE / TARRAZU--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(105,SEQ_DISTRICT.NEXTVAL,'SAN MARCOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(105,SEQ_DISTRICT.NEXTVAL,'SAN LORENZO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(105,SEQ_DISTRICT.NEXTVAL,'SAN CARLOS');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,106,'ASERRI');
--DISTRITOS SAN JOSE / ASERRI--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(106,SEQ_DISTRICT.NEXTVAL,'ASERRI');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(106,SEQ_DISTRICT.NEXTVAL,'TARBACA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(106,SEQ_DISTRICT.NEXTVAL,'VUELTA DE JORCO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(106,SEQ_DISTRICT.NEXTVAL,'SAN GABRIEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(106,SEQ_DISTRICT.NEXTVAL,'LEGUA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(106,SEQ_DISTRICT.NEXTVAL,'MONTERREY');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(106,SEQ_DISTRICT.NEXTVAL,'SALITRILLOS');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,107,'MORA');
--DISTRITOS SAN JOSE / MORA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(107,SEQ_DISTRICT.NEXTVAL,'COLON');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(107,SEQ_DISTRICT.NEXTVAL,'GUAYABO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(107,SEQ_DISTRICT.NEXTVAL,'TABARCIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(107,SEQ_DISTRICT.NEXTVAL,'PIEDRAS NEGRAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(107,SEQ_DISTRICT.NEXTVAL,'PICAGRES');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,108,'GOICOCHEA');
--DISTRITOS SAN JOSE / GOICOCHEA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(108,SEQ_DISTRICT.NEXTVAL,'GUADALUPE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(108,SEQ_DISTRICT.NEXTVAL,'SAN FRANCISCO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(108,SEQ_DISTRICT.NEXTVAL,'CALLE BLANCOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(108,SEQ_DISTRICT.NEXTVAL,'MATA DE PLATANO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(108,SEQ_DISTRICT.NEXTVAL,'IPIS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(108,SEQ_DISTRICT.NEXTVAL,'RANCHO REDONDO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(108,SEQ_DISTRICT.NEXTVAL,'PURRAL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,109,'SANTA ANA');
--DISTRITOS SAN JOSE / SANTA ANA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(109,SEQ_DISTRICT.NEXTVAL,'SANTA ANA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(109,SEQ_DISTRICT.NEXTVAL,'SALITRAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(109,SEQ_DISTRICT.NEXTVAL,'POZOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(109,SEQ_DISTRICT.NEXTVAL,'URUCA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(109,SEQ_DISTRICT.NEXTVAL,'PIEDADES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(109,SEQ_DISTRICT.NEXTVAL,'BRASIL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,110,'ALAJUELITA');
--DISTRITOS SAN JOSE / ALAJUELITA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(110,SEQ_DISTRICT.NEXTVAL,'ALAJUELITA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(110,SEQ_DISTRICT.NEXTVAL,'SAN JOSECITO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(110,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(110,SEQ_DISTRICT.NEXTVAL,'CONCEPCION');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(110,SEQ_DISTRICT.NEXTVAL,'SAN FELIPE');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,111,'VAZQUEZ DE CORONADO');
--DISTRITOS SAN JOSE / VAZQUEZ DE CORONADO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(111,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(111,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(111,SEQ_DISTRICT.NEXTVAL,'DULCE NOMBRE DE JESUS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(111,SEQ_DISTRICT.NEXTVAL,'PATALILLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(111,SEQ_DISTRICT.NEXTVAL,'CASCAJAL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,112,'ACOSTA');
--DISTRITOS SAN JOSE / ACOSTA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(112,SEQ_DISTRICT.NEXTVAL,'SAN IGNACIO DE ACOSTA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(112,SEQ_DISTRICT.NEXTVAL,'GUAITIL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(112,SEQ_DISTRICT.NEXTVAL,'PALMICHAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(112,SEQ_DISTRICT.NEXTVAL,'CANGREJAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(112,SEQ_DISTRICT.NEXTVAL,'SABANILLAS');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,113,'TIBAS');
--DISTRITOS SAN JOSE / TIBAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(113,SEQ_DISTRICT.NEXTVAL,'SAN JUAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(113,SEQ_DISTRICT.NEXTVAL,'CINCO ESQUINAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(113,SEQ_DISTRICT.NEXTVAL,'ANSELMO LLORENTE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(113,SEQ_DISTRICT.NEXTVAL,'LEON XIII');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(113,SEQ_DISTRICT.NEXTVAL,'COLIMA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,114,'MORAVIA');
--DISTRITOS SAN JOSE / MORAVIA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(114,SEQ_DISTRICT.NEXTVAL,'SAN VICENTE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(114,SEQ_DISTRICT.NEXTVAL,'SAN GERONIMO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(114,SEQ_DISTRICT.NEXTVAL,'TRINIDAD');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,115,'MONTES DE OCA');
--DISTRITOS SAN JOSE / MONTES DE OCA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(115,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(115,SEQ_DISTRICT.NEXTVAL,'SABANILLA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(115,SEQ_DISTRICT.NEXTVAL,'MERCEDES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(115,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,116,'TURRUBARES');
--DISTRITOS SAN JOSE / TURRUBARES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(116,SEQ_DISTRICT.NEXTVAL,'SAN PABLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(116,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(116,SEQ_DISTRICT.NEXTVAL,'SAN JUAN DE MATA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(116,SEQ_DISTRICT.NEXTVAL,'SAN LUIS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(116,SEQ_DISTRICT.NEXTVAL,'CARANA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,117,'DOTA');
--DISTRITOS SAN JOSE / DOTA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(117,SEQ_DISTRICT.NEXTVAL,'SANTA MARIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(117,SEQ_DISTRICT.NEXTVAL,'JARDIN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(117,SEQ_DISTRICT.NEXTVAL,'COPEY');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,118,'CURRIDABAT');
--DISTRITOS SAN JOSE / CURRIDABAT--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(118,SEQ_DISTRICT.NEXTVAL,'CURRIDABAT');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(118,SEQ_DISTRICT.NEXTVAL,'GRANADILLA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(118,SEQ_DISTRICT.NEXTVAL,'SANCHEZ');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(118,SEQ_DISTRICT.NEXTVAL,'TIRRASES');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,119,'PEREZ ZELEDON');
--DISTRITOS SAN JOSE / PEREZ ZELEDON--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO DEL GENERA;');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'GENERAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'DANIEL FLORES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'RIVAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'PLATANARES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'PEJIBAYE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'CAJON');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'BARU');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'RIO NUEVO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(119,SEQ_DISTRICT.NEXTVAL,'PARAMO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,120,'LEON CORTES');
--DISTRITOS SAN JOSE / LEON CORTES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SAN PABLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SAN ANDRES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(120,SEQ_DISTRICT.NEXTVAL,'LLANO BONITO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SANTA CRUZ');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO');




--                                      ************************
--                                      |       ALAJUELA       |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,201,'ALAJUELA');
--DISTRITOS ALAJUELA / ALAJUELA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'ALAJUELA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SAN JOSE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'CARRIZAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'GUACIMA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SABANILLA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'RIO SEGUNDO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'DESAMPARADOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'TURRUCARES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'TAMBOR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'GARITA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SARAPIQUI');

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,202,'SAN RAMON');
--DISTRITOS ALAJUELA / SAN RAMON--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SAN RAMON');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SANTIAGO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SAN JUAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'PIEDADES NORTE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'PIEDADES SUR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'ANGELES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'ALAFARO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'VOLIO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'CONCEPCION');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'ZAPOTAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(202,SEQ_DISTRICT.NEXTVAL,'PEÑAS BLANCAS');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,203,'GRECIA');
--DISTRITOS ALAJUELA / GRECIA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(203,SEQ_DISTRICT.NEXTVAL,'GRECIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(203,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(203,SEQ_DISTRICT.NEXTVAL,'SAN JOSE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(203,SEQ_DISTRICT.NEXTVAL,'SAN ROQUE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(203,SEQ_DISTRICT.NEXTVAL,'TACARES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(203,SEQ_DISTRICT.NEXTVAL,'RIO CUARTO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(203,SEQ_DISTRICT.NEXTVAL,'PUENTE DE PIEDRA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(203,SEQ_DISTRICT.NEXTVAL,'BOLIVAR');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,204,'SAN MATEO');
--DISTRITOS ALAJUELA / SAN MATEO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(204,SEQ_DISTRICT.NEXTVAL,'SAN MATEO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(204,SEQ_DISTRICT.NEXTVAL,'DESMONTES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(204,SEQ_DISTRICT.NEXTVAL,'JESUS MARIA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,205,'ATENAS');
--DISTRITOS ALAJUELA / ATENAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(205,SEQ_DISTRICT.NEXTVAL,'ATENAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(205,SEQ_DISTRICT.NEXTVAL,'JESUS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(205,SEQ_DISTRICT.NEXTVAL,'MERCEDES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(205,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(205,SEQ_DISTRICT.NEXTVAL,'CONCEPCION');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(205,SEQ_DISTRICT.NEXTVAL,'SAN JOSE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(205,SEQ_DISTRICT.NEXTVAL,'SANTA EULALIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(205,SEQ_DISTRICT.NEXTVAL,'ESCOBAL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,206,'NARANJO');
--DISTRITOS ALAJUELA / NARANJO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(206,SEQ_DISTRICT.NEXTVAL,'NARANJO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(206,SEQ_DISTRICT.NEXTVAL,'SAN MIGUEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(206,SEQ_DISTRICT.NEXTVAL,'SAN JOSE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(206,SEQ_DISTRICT.NEXTVAL,'CIRRI SUR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(206,SEQ_DISTRICT.NEXTVAL,'SAN JERONIMO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(206,SEQ_DISTRICT.NEXTVAL,'SAN JUAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(206,SEQ_DISTRICT.NEXTVAL,'ROSARIO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,207,'PALMARES');
--DISTRITOS ALAJUELA / PALMARES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(207,SEQ_DISTRICT.NEXTVAL,'PALMARES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(207,SEQ_DISTRICT.NEXTVAL,'ZARAGOZA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(207,SEQ_DISTRICT.NEXTVAL,'BUENOS AIRES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(207,SEQ_DISTRICT.NEXTVAL,'SANTIAGO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(207,SEQ_DISTRICT.NEXTVAL,'CANDELARIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(207,SEQ_DISTRICT.NEXTVAL,'ESQUIPULAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(207,SEQ_DISTRICT.NEXTVAL,'GRANJA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,208,'POAS');
--DISTRITOS ALAJUELA / POAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(208,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(208,SEQ_DISTRICT.NEXTVAL,'SAN JUAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(208,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(208,SEQ_DISTRICT.NEXTVAL,'CARRILLOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(208,SEQ_DISTRICT.NEXTVAL,'SABANA REDONDA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,209,'OROTINA');
--DISTRITOS ALAJUELA / OROTINA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(209,SEQ_DISTRICT.NEXTVAL,'OROTINA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(209,SEQ_DISTRICT.NEXTVAL,'MASTATE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(209,SEQ_DISTRICT.NEXTVAL,'HACIENDA VIEJA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(209,SEQ_DISTRICT.NEXTVAL,'COYOLAR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(209,SEQ_DISTRICT.NEXTVAL,'CEIBA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,210,'SAN CARLOS');
--DISTRITOS ALAJUELA / SAN CARLOS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'QUESADA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'FLORENCIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'BUENAVISTA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'AGUAS ZARCAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'VENECIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'PITAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'FORTUNA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'TIGRA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'PALMERA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'VENADO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'CUTRIS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(210,SEQ_DISTRICT.NEXTVAL,'MONTERREY');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,211,'ALFARO RUIZ');
--DISTRITOS ALAJUELA / ALFARO RUIZ--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(211,SEQ_DISTRICT.NEXTVAL,'ZARCERO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(211,SEQ_DISTRICT.NEXTVAL,'LAGUNA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(211,SEQ_DISTRICT.NEXTVAL,'TAPEZCO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(211,SEQ_DISTRICT.NEXTVAL,'GUADALUPE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(211,SEQ_DISTRICT.NEXTVAL,'PALMIRA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(211,SEQ_DISTRICT.NEXTVAL,'ZAPOTE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(211,SEQ_DISTRICT.NEXTVAL,'BRISAS');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,212,'VALVERDE VEGA');
--DISTRITOS ALAJUELA / VALVERDE VEGA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(212,SEQ_DISTRICT.NEXTVAL,'SARCHI NORTE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(212,SEQ_DISTRICT.NEXTVAL,'SARCHI SUR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(212,SEQ_DISTRICT.NEXTVAL,'TORO AMARILLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(212,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(212,SEQ_DISTRICT.NEXTVAL,'RODRIGUEZ');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,213,'UPALA');
--DISTRITOS ALAJUELA / UPALA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(213,SEQ_DISTRICT.NEXTVAL,'UPALA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(213,SEQ_DISTRICT.NEXTVAL,'AGUAS CLARAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(213,SEQ_DISTRICT.NEXTVAL,'SAN JOSE(PIZOTE)');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(213,SEQ_DISTRICT.NEXTVAL,'BIJAGUA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(213,SEQ_DISTRICT.NEXTVAL,'DELICIAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(213,SEQ_DISTRICT.NEXTVAL,'DOS RIOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(213,SEQ_DISTRICT.NEXTVAL,'YOLIYLLAL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,214,'LOS CHILES');
--DISTRITOS ALAJUELA / LOS CHILES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(214,SEQ_DISTRICT.NEXTVAL,'LOS CHILES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(214,SEQ_DISTRICT.NEXTVAL,'CAÑO NEGRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(214,SEQ_DISTRICT.NEXTVAL,'EL AMPARO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(214,SEQ_DISTRICT.NEXTVAL,'SAN JORGE');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,215,'GUATUSO');
--DISTRITOS ALAJUELA / GUATUSO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(215,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(215,SEQ_DISTRICT.NEXTVAL,'BUENA VISTA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(215,SEQ_DISTRICT.NEXTVAL,'COTE');




--                                      ************************
--                                      |       CARTAGO        |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,301,'CARTAGO');
--DISTRITOS CARTAGO / CARTAGO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'ORIENTAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'OCCIDENTAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'CARMEN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'SAN NICOLAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'AGUACALIENTE (SAN FRANCISCO)');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'GUADALUPE (ARENILLA)');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'CORRALILLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'TIERRA BLANCA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'DULCE NOMBRE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'LLANO GRANDE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(301,SEQ_DISTRICT.NEXTVAL,'QUEBRADILLA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,302,'PARAISO');
--DISTRITOS CARTAGO / PARAISO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(302,SEQ_DISTRICT.NEXTVAL,'PARAISO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(302,SEQ_DISTRICT.NEXTVAL,'SANTIAGO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(302,SEQ_DISTRICT.NEXTVAL,'OROSI');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(302,SEQ_DISTRICT.NEXTVAL,'CACHI');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(302,SEQ_DISTRICT.NEXTVAL,'LLANOS DE SANTA LUCIA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,303,'LA UNION');
--DISTRITOS CARTAGO / LA UNION--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(303,SEQ_DISTRICT.NEXTVAL,'TRES RIOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(303,SEQ_DISTRICT.NEXTVAL,'SAN DIEGO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(303,SEQ_DISTRICT.NEXTVAL,'SAN JUAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(303,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(303,SEQ_DISTRICT.NEXTVAL,'CONCEPCION');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(303,SEQ_DISTRICT.NEXTVAL,'DULCE NOMBRE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(303,SEQ_DISTRICT.NEXTVAL,'SAN RAMON');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(303,SEQ_DISTRICT.NEXTVAL,'RIO AZUL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,304,'JIMENEZ');
--DISTRITOS CARTAGO / JIMENEZ--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(304,SEQ_DISTRICT.NEXTVAL,'JUAN VIÑAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(304,SEQ_DISTRICT.NEXTVAL,'TUCURRIQUE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(304,SEQ_DISTRICT.NEXTVAL,'PEJIBAYE');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,305,'TURRIALBA');
--DISTRITOS CARTAGO / TURRIALBA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'TURRIALBA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'LA SUIZA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'PERALTA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'SANTA CRUZ');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'SANTA TERESITA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'PAVONES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'TUIS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'TAYUTIC');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'SANTA ROSA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'TRES EQUIS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'LA ISABEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(305,SEQ_DISTRICT.NEXTVAL,'CHIRRIPO');

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,306,'ALVARADO');
--DISTRITOS CARTAGO / ALVARADO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(306,SEQ_DISTRICT.NEXTVAL,'PACAYAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(306,SEQ_DISTRICT.NEXTVAL,'CERVANTES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(306,SEQ_DISTRICT.NEXTVAL,'CAPELLADES');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,307,'OREAMUNO');
--DISTRITOS CARTAGO / OREAMUNO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(307,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(307,SEQ_DISTRICT.NEXTVAL,'COTE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(307,SEQ_DISTRICT.NEXTVAL,'POTRERO CERRADO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(307,SEQ_DISTRICT.NEXTVAL,'CIPRESES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(307,SEQ_DISTRICT.NEXTVAL,'SANTA ROSA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,308,'EL GUARCO');
--DISTRITOS CARTAGO / EL GUARCO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(308,SEQ_DISTRICT.NEXTVAL,'TEJAR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(308,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(308,SEQ_DISTRICT.NEXTVAL,'TOBOSI');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(308,SEQ_DISTRICT.NEXTVAL,'PATIO DE AGUA');




--                                      ************************
--                                      |       HEREDIA        |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,401,'HEREDIA');
--DISTRITOS HEREDIA / HEREDIA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(401,SEQ_DISTRICT.NEXTVAL,'HEREDIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(401,SEQ_DISTRICT.NEXTVAL,'MERCEDES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(401,SEQ_DISTRICT.NEXTVAL,'SAN FRANCISCO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(401,SEQ_DISTRICT.NEXTVAL,'ULLOA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(401,SEQ_DISTRICT.NEXTVAL,'VARABLANCA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,402,'BARVA');
--DISTRITOS HEREDIA / BARVA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(402,SEQ_DISTRICT.NEXTVAL,'BARVA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SAN PABLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SAN ROQUE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SANTA LUCIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SAN JOSE DE LA MONTAÑA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,403,'SANTO DOMINGO');
--DISTRITOS HEREDIA / SANTO DOMINGO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SANTO DOMINGO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SAN VICENTE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SAN MIGUEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(403,SEQ_DISTRICT.NEXTVAL,'PARACITO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SANTO TOMAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SANTA ROSA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(403,SEQ_DISTRICT.NEXTVAL,'TURES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(403,SEQ_DISTRICT.NEXTVAL,'PARA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,404,'SANTA BARBARA');
--DISTRITOS HEREDIA / SANTA BARBARA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(404,SEQ_DISTRICT.NEXTVAL,'SANTA BARBARA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(404,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(404,SEQ_DISTRICT.NEXTVAL,'SAN JUAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(404,SEQ_DISTRICT.NEXTVAL,'JESUS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(404,SEQ_DISTRICT.NEXTVAL,'SANTO DOMINGO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(404,SEQ_DISTRICT.NEXTVAL,'PURABA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,405,'SAN RAFAEL');
--DISTRITOS HEREDIA / SAN RAFAEL--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(405,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(405,SEQ_DISTRICT.NEXTVAL,'SAN JOSECITO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(405,SEQ_DISTRICT.NEXTVAL,'SANTIAGO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(405,SEQ_DISTRICT.NEXTVAL,'ANGELES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(405,SEQ_DISTRICT.NEXTVAL,'CONCEPCION');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,406,'SAN ISIDRO');
--DISTRITOS HEREDIA / SAN ISIDRO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(406,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(406,SEQ_DISTRICT.NEXTVAL,'SAN JOSE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(406,SEQ_DISTRICT.NEXTVAL,'CONCEPCION');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(406,SEQ_DISTRICT.NEXTVAL,'SAN FRANCISCO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,407,'BELEN');
--DISTRITOS HEREDIA / BELEN--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(407,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(407,SEQ_DISTRICT.NEXTVAL,'RIBERA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(407,SEQ_DISTRICT.NEXTVAL,'ASUNCION');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,408,'SAN JOAQUIN DE FLORES');
--DISTRITOS HEREDIA / SAN JOAQUIN DE FLORES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(408,SEQ_DISTRICT.NEXTVAL,'SAN JOAQUIN DE FLORES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(408,SEQ_DISTRICT.NEXTVAL,'BARRANTES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(408,SEQ_DISTRICT.NEXTVAL,'LLORENTE');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,409,'SAN PABLO');
--DISTRITOS HEREDIA / SAN PABLO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(409,SEQ_DISTRICT.NEXTVAL,'SAN PABLO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,410,'SARAPIQUI');
--DISTRITOS HEREDIA / SARAPIQUI--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(410,SEQ_DISTRICT.NEXTVAL,'PUERTO VIEJO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(410,SEQ_DISTRICT.NEXTVAL,'LA VIRGEN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(410,SEQ_DISTRICT.NEXTVAL,'HORQUETAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(410,SEQ_DISTRICT.NEXTVAL,'LLANURAS DEL GASPAR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(410,SEQ_DISTRICT.NEXTVAL,'CUREÑA');




--                                      ************************
--                                      |      GUANACASTE      |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,501,'LIBERIA');
--DISTRITOS GUANACASTE / LIBERIA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(501,SEQ_DISTRICT.NEXTVAL,'LIBERIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(501,SEQ_DISTRICT.NEXTVAL,'CAÑAS DULCES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(501,SEQ_DISTRICT.NEXTVAL,'MAYORGA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(501,SEQ_DISTRICT.NEXTVAL,'NACASCOLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(501,SEQ_DISTRICT.NEXTVAL,'CURUBANDE');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,502,'NICOYA');
--DISTRITOS GUANACASTE / NICOYA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(502,SEQ_DISTRICT.NEXTVAL,'NICOYA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(502,SEQ_DISTRICT.NEXTVAL,'MANSION');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(502,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(502,SEQ_DISTRICT.NEXTVAL,'QUEBRADA HONDA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(502,SEQ_DISTRICT.NEXTVAL,'SAMARA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(502,SEQ_DISTRICT.NEXTVAL,'NOSARA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(502,SEQ_DISTRICT.NEXTVAL,'BELEN DE NOSARITA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,503,'SANTA CRUZ');
--DISTRITOS GUANACASTE / SANTA CRUZ--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(503,SEQ_DISTRICT.NEXTVAL,'SANTA CRUZ');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(503,SEQ_DISTRICT.NEXTVAL,'BOLSON');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(503,SEQ_DISTRICT.NEXTVAL,'VEINTISIETE DE ABRIL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(503,SEQ_DISTRICT.NEXTVAL,'TEMPATE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(503,SEQ_DISTRICT.NEXTVAL,'CARTAGENA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(503,SEQ_DISTRICT.NEXTVAL,'CUAJINIQUIL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(503,SEQ_DISTRICT.NEXTVAL,'DIRIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(503,SEQ_DISTRICT.NEXTVAL,'CABO VELAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(503,SEQ_DISTRICT.NEXTVAL,'TAMARINDO');

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,504,'BAGACES');
--DISTRITOS GUANACASTE / VAGACES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(504,SEQ_DISTRICT.NEXTVAL,'BAGACES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(504,SEQ_DISTRICT.NEXTVAL,'FORTUNA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(504,SEQ_DISTRICT.NEXTVAL,'MOGOTE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(504,SEQ_DISTRICT.NEXTVAL,'RIO NARANJO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,505,'CARRILLO');
--DISTRITOS GUANACASTE / CARRILLO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(505,SEQ_DISTRICT.NEXTVAL,'FILADELFIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(505,SEQ_DISTRICT.NEXTVAL,'PALMIRA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(505,SEQ_DISTRICT.NEXTVAL,'SARDINAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(505,SEQ_DISTRICT.NEXTVAL,'BELEN');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,506,'CAÑAS');
--DISTRITOS GUANACASTE / CAÑAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(506,SEQ_DISTRICT.NEXTVAL,'CAÑAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(506,SEQ_DISTRICT.NEXTVAL,'PALMIRA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(506,SEQ_DISTRICT.NEXTVAL,'SAN MIGUEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(506,SEQ_DISTRICT.NEXTVAL,'BEBEDERO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(506,SEQ_DISTRICT.NEXTVAL,'POROZAL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,507,'ABANGARES');
--DISTRITOS GUANACASTE / ABANGARES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(507,SEQ_DISTRICT.NEXTVAL,'JUNTAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(507,SEQ_DISTRICT.NEXTVAL,'SIERRA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(507,SEQ_DISTRICT.NEXTVAL,'SAN JUAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(507,SEQ_DISTRICT.NEXTVAL,'COLORADO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,508,'TILARAN');
--DISTRITOS GUANACASTE / TILARAN--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(508,SEQ_DISTRICT.NEXTVAL,'TILARAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(508,SEQ_DISTRICT.NEXTVAL,'QUEBRADA GRANDE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(508,SEQ_DISTRICT.NEXTVAL,'TRONADORA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(508,SEQ_DISTRICT.NEXTVAL,'SANTA ROSA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(508,SEQ_DISTRICT.NEXTVAL,'LIBANO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(508,SEQ_DISTRICT.NEXTVAL,'TIERRAS MORENAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(508,SEQ_DISTRICT.NEXTVAL,'ARENAL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,509,'NANDAYURE');
--DISTRITOS GUANACASTE / NANDAYURE--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(509,SEQ_DISTRICT.NEXTVAL,'CARMONA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(509,SEQ_DISTRICT.NEXTVAL,'SANTA RITA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(509,SEQ_DISTRICT.NEXTVAL,'ZAPOTAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(509,SEQ_DISTRICT.NEXTVAL,'SAN PABLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(509,SEQ_DISTRICT.NEXTVAL,'PORVENIR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(509,SEQ_DISTRICT.NEXTVAL,'BEJUCO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,510,'LA CRUZ');
--DISTRITOS GUANACASTE / LA CRUZ--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(510,SEQ_DISTRICT.NEXTVAL,'LA CRUZ');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(510,SEQ_DISTRICT.NEXTVAL,'SANTA CECILIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(510,SEQ_DISTRICT.NEXTVAL,'GARITA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(510,SEQ_DISTRICT.NEXTVAL,'SANTA ELENA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,511,'HOJANCHA');
--DISTRITOS GUANACASTE / HOJANCHA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(511,SEQ_DISTRICT.NEXTVAL,'HOJANCHA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(511,SEQ_DISTRICT.NEXTVAL,'MONTE ROMO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(511,SEQ_DISTRICT.NEXTVAL,'PUERTO CARRILLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(511,SEQ_DISTRICT.NEXTVAL,'HUACAS');




--                                      ************************
--                                      |      PUNTARENAS      |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,601,'PUNTARENAS');
--DISTRITOS PUNTARENAS / PUNTARENAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'PUNTARENAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'PITAHAYA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'CHOMES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'LEPANTO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'PAQUERA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'MANZANILLO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'GUACIMAL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'BARRANCA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'MONTE VERDE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'ISLA DEL COCO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'COBANO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'CHACARICA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'CHIRA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'ACAPULCO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'EL ROBLE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(601,SEQ_DISTRICT.NEXTVAL,'ARANCIBIA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,602,'ESPARZA');
--DISTRITOS PUNTARENAS / ESPARZA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(602,SEQ_DISTRICT.NEXTVAL,'ESPIRITU SANTO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(602,SEQ_DISTRICT.NEXTVAL,'SAN JUAN GRANDE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(602,SEQ_DISTRICT.NEXTVAL,'MACACONA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(602,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(602,SEQ_DISTRICT.NEXTVAL,'SAN GERONIMO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,603,'BUENOS AIRES');
--DISTRITOS PUNTARENAS / BUANOS AIRES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(603,SEQ_DISTRICT.NEXTVAL,'BUENOS AIRES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(603,SEQ_DISTRICT.NEXTVAL,'VOLCAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(603,SEQ_DISTRICT.NEXTVAL,'POTRERO GRANDE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(603,SEQ_DISTRICT.NEXTVAL,'BORUCA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(603,SEQ_DISTRICT.NEXTVAL,'PILAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(603,SEQ_DISTRICT.NEXTVAL,'COLINAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(603,SEQ_DISTRICT.NEXTVAL,'CHANGENA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(603,SEQ_DISTRICT.NEXTVAL,'BRIOLLEY');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(603,SEQ_DISTRICT.NEXTVAL,'BRUNKA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,604,'MONTES DE ORO');
--DISTRITOS PUNTARENAS / MONTES DE ORO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(604,SEQ_DISTRICT.NEXTVAL,'MIRAMAR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(604,SEQ_DISTRICT.NEXTVAL,'UNION');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(604,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,605,'OSA');
--DISTRITOS PUNTARENAS / OSA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(605,SEQ_DISTRICT.NEXTVAL,'PUERTO CORTES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(605,SEQ_DISTRICT.NEXTVAL,'PALMAR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(605,SEQ_DISTRICT.NEXTVAL,'SIERPE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(605,SEQ_DISTRICT.NEXTVAL,'BAHIA BALLENA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(605,SEQ_DISTRICT.NEXTVAL,'PIEDRAS BLANCAS');

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,606,'AGUIRRE');
--DISTRITOS PUNTARENAS / AGUIRRE--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(606,SEQ_DISTRICT.NEXTVAL,'QUEPOS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(606,SEQ_DISTRICT.NEXTVAL,'SAVEGRE');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(606,SEQ_DISTRICT.NEXTVAL,'NARANJITO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,607,'GOLFITO');
--DISTRITOS PUNTARENAS / GOLFITO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(607,SEQ_DISTRICT.NEXTVAL,'GOLFITO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(607,SEQ_DISTRICT.NEXTVAL,'PUERTO JIMENEZ');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(607,SEQ_DISTRICT.NEXTVAL,'GUAYCARA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(607,SEQ_DISTRICT.NEXTVAL,'PAVON');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,608,'COTO BRUS');
--DISTRITOS PUNTARENAS / COTO BRUS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(608,SEQ_DISTRICT.NEXTVAL,'SAN VITO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(608,SEQ_DISTRICT.NEXTVAL,'SABALITO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(608,SEQ_DISTRICT.NEXTVAL,'AGUABUENA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(608,SEQ_DISTRICT.NEXTVAL,'LIMONCITO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(608,SEQ_DISTRICT.NEXTVAL,'PITTIER');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,609,'PARRITA');
--DISTRITOS PUNTARENAS / PARRITA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(609,SEQ_DISTRICT.NEXTVAL,'PARRITA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,610,'CORREDORES');
--DISTRITOS PUNTARENAS / CORREDORES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(610,SEQ_DISTRICT.NEXTVAL,'CORREDOR');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(610,SEQ_DISTRICT.NEXTVAL,'LA CUESTA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(610,SEQ_DISTRICT.NEXTVAL,'CANOAS');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(610,SEQ_DISTRICT.NEXTVAL,'LAUREL');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,611,'GARABITO');
--DISTRITOS PUNTARENAS / GARABITO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(611,SEQ_DISTRICT.NEXTVAL,'JACO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(611,SEQ_DISTRICT.NEXTVAL,'TARCOLES');




--                                      ************************
--                                      |        LIMON         |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,701,'LIMON');
--DISTRITOS LIMON / LIMON--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(701,SEQ_DISTRICT.NEXTVAL,'LIMON');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(701,SEQ_DISTRICT.NEXTVAL,'VALLE LA ESTRELLA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(701,SEQ_DISTRICT.NEXTVAL,'RIO BLANCO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(701,SEQ_DISTRICT.NEXTVAL,'MATAMA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,702,'POCOCI');
--DISTRITOS LIMON / POCOCI--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(702,SEQ_DISTRICT.NEXTVAL,'GUAPILES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(702,SEQ_DISTRICT.NEXTVAL,'JIMENEZ');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(702,SEQ_DISTRICT.NEXTVAL,'RITA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(702,SEQ_DISTRICT.NEXTVAL,'ROXANA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(702,SEQ_DISTRICT.NEXTVAL,'CARIARI');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(702,SEQ_DISTRICT.NEXTVAL,'COLORADO');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,703,'SIQUIRRES');
--DISTRITOS LIMON / SIQUIRRES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(703,SEQ_DISTRICT.NEXTVAL,'SIQUIRRES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(703,SEQ_DISTRICT.NEXTVAL,'PACUARITO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(703,SEQ_DISTRICT.NEXTVAL,'FLORIDA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(703,SEQ_DISTRICT.NEXTVAL,'GERMANIA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(703,SEQ_DISTRICT.NEXTVAL,'CAIRO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(703,SEQ_DISTRICT.NEXTVAL,'ALEGRIA');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,704,'TALAMANCA');
--DISTRITOS LIMON / TALAMANCA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(704,SEQ_DISTRICT.NEXTVAL,'BRATSI');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(704,SEQ_DISTRICT.NEXTVAL,'SIXAOLA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(704,SEQ_DISTRICT.NEXTVAL,'CAHUITA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(704,SEQ_DISTRICT.NEXTVAL,'TELIRE');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,705,'MATINA');
--DISTRITOS LIMON / MATINA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(705,SEQ_DISTRICT.NEXTVAL,'MATINA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(705,SEQ_DISTRICT.NEXTVAL,'BATTAN');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(705,SEQ_DISTRICT.NEXTVAL,'CARRANDI');


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,706,'GUACIMO');
--DISTRITOS LIMON / GUACIMO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(706,SEQ_DISTRICT.NEXTVAL,'GUACIMO');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(706,SEQ_DISTRICT.NEXTVAL,'MERDECES');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(706,SEQ_DISTRICT.NEXTVAL,'POCORA');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(706,SEQ_DISTRICT.NEXTVAL,'RIO JIMENEZ');
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME) VALUES(706,SEQ_DISTRICT.NEXTVAL,'DUACARI');

COMMIT;