--                              ***************************************
--                                  INSERT PROVINCES FROM COSTA RICA
--                              ***************************************
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 1, 'San Jose');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 2, 'Alajuela');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 3, 'Cartago');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 4, 'Heredia');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 5, 'Guanacaste');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 6, 'Puntarenas');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 7, 'Limon');

CREATE SEQUENCE SEQ_DISTRICT
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE
ORDER;




--                                      ************************
--                                      |       SAN JOSE       |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,101,'SAN JOSE');
--DISTRITOS SAN JOSE / SAN JOSE--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'CARMEN',9.9359945,-84.06695450000001);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'MERCED',9.940562700000001,-84.08940430000001);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'HOSPITAL',9.9252418,-84.08808390000002);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'CATEDRAL',9.9249628,-84.07223750000003);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'ZAPOTE',9.9191024,-84.05966699999999);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'SAN FRANCISCO DE DOS RIOS',9.9080918,-84.06167089999997);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'URUCA',9.959179299999999,-84.11976429999999);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'MATA REDONDA',9.936738199999999,-84.10920599999997);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'PAVAS',9.945407099999999,-84.1276818);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'HATILLO',9.9199576,-84.10392619999999);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(101,SEQ_DISTRICT.NEXTVAL,'SAN SEBASTIAN',9.9084637,-84.08280230000003);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,102,'ESCAZU');
--DISTRITOS SAN JOSE / ESCAZU--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(102,SEQ_DISTRICT.NEXTVAL,'ESCAZU',9.920695,-84.1461519);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(102,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO',9.889304573544125,-84.13839201166991);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(102,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',9.9346483,-84.14878999999996);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,103,'DESAMPARADOS');
--DISTRITOS SAN JOSE / DESAMPARADOS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'DESAMPARADOS',9.8969706,-84.06167089999997);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN MIGUEL',9.8761455,-84.06299189999999);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN JUAN DE DIOS',9.8775972,-84.08509240000001);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL ARRIBA',9.876801799999999,-84.07373519999999);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO',9.8989015,-84.04703180000001);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'FRAILES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'PATARRA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN CRISTOBAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'ROSARIO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'DAMAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL ABAJO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(103,SEQ_DISTRICT.NEXTVAL,'GRAVILIAS',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,104,'PURISCAL');
--DISTRITOS SAN JOSE / PURISCAL--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(104,SEQ_DISTRICT.NEXTVAL,'SANTIAGO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(104,SEQ_DISTRICT.NEXTVAL,'MERCEDES SUR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(104,SEQ_DISTRICT.NEXTVAL,'BARBACOAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(104,SEQ_DISTRICT.NEXTVAL,'GRIFO ALTO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(104,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(104,SEQ_DISTRICT.NEXTVAL,'CANDELARIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(104,SEQ_DISTRICT.NEXTVAL,'DESAMPARADITOS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(104,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(104,SEQ_DISTRICT.NEXTVAL,'CHIRES',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,105,'TARRAZU');
--DISTRITOS SAN JOSE / TARRAZU--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(105,SEQ_DISTRICT.NEXTVAL,'SAN MARCOS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(105,SEQ_DISTRICT.NEXTVAL,'SAN LORENZO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(105,SEQ_DISTRICT.NEXTVAL,'SAN CARLOS',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,106,'ASERRI');
--DISTRITOS SAN JOSE / ASERRI--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(106,SEQ_DISTRICT.NEXTVAL,'ASERRI',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(106,SEQ_DISTRICT.NEXTVAL,'TARBACA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(106,SEQ_DISTRICT.NEXTVAL,'VUELTA DE JORCO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(106,SEQ_DISTRICT.NEXTVAL,'SAN GABRIEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(106,SEQ_DISTRICT.NEXTVAL,'LEGUA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(106,SEQ_DISTRICT.NEXTVAL,'MONTERREY',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(106,SEQ_DISTRICT.NEXTVAL,'SALITRILLOS',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,107,'MORA');
--DISTRITOS SAN JOSE / MORA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(107,SEQ_DISTRICT.NEXTVAL,'COLON',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(107,SEQ_DISTRICT.NEXTVAL,'GUAYABO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(107,SEQ_DISTRICT.NEXTVAL,'TABARCIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(107,SEQ_DISTRICT.NEXTVAL,'PIEDRAS NEGRAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(107,SEQ_DISTRICT.NEXTVAL,'PICAGRES',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,108,'GOICOCHEA');
--DISTRITOS SAN JOSE / GOICOCHEA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(108,SEQ_DISTRICT.NEXTVAL,'GUADALUPE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(108,SEQ_DISTRICT.NEXTVAL,'SAN FRANCISCO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(108,SEQ_DISTRICT.NEXTVAL,'CALLE BLANCOS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(108,SEQ_DISTRICT.NEXTVAL,'MATA DE PLATANO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(108,SEQ_DISTRICT.NEXTVAL,'IPIS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(108,SEQ_DISTRICT.NEXTVAL,'RANCHO REDONDO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(108,SEQ_DISTRICT.NEXTVAL,'PURRAL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,109,'SANTA ANA');
--DISTRITOS SAN JOSE / SANTA ANA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(109,SEQ_DISTRICT.NEXTVAL,'SANTA ANA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(109,SEQ_DISTRICT.NEXTVAL,'SALITRAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(109,SEQ_DISTRICT.NEXTVAL,'POZOS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(109,SEQ_DISTRICT.NEXTVAL,'URUCA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(109,SEQ_DISTRICT.NEXTVAL,'PIEDADES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(109,SEQ_DISTRICT.NEXTVAL,'BRASIL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,110,'ALAJUELITA');
--DISTRITOS SAN JOSE / ALAJUELITA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(110,SEQ_DISTRICT.NEXTVAL,'ALAJUELITA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(110,SEQ_DISTRICT.NEXTVAL,'SAN JOSECITO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(110,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(110,SEQ_DISTRICT.NEXTVAL,'CONCEPCION',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(110,SEQ_DISTRICT.NEXTVAL,'SAN FELIPE',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,111,'VAZQUEZ DE CORONADO');
--DISTRITOS SAN JOSE / VAZQUEZ DE CORONADO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(111,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(111,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(111,SEQ_DISTRICT.NEXTVAL,'DULCE NOMBRE DE JESUS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(111,SEQ_DISTRICT.NEXTVAL,'PATALILLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(111,SEQ_DISTRICT.NEXTVAL,'CASCAJAL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,112,'ACOSTA');
--DISTRITOS SAN JOSE / ACOSTA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(112,SEQ_DISTRICT.NEXTVAL,'SAN IGNACIO DE ACOSTA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(112,SEQ_DISTRICT.NEXTVAL,'GUAITIL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(112,SEQ_DISTRICT.NEXTVAL,'PALMICHAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(112,SEQ_DISTRICT.NEXTVAL,'CANGREJAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(112,SEQ_DISTRICT.NEXTVAL,'SABANILLAS',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,113,'TIBAS');
--DISTRITOS SAN JOSE / TIBAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(113,SEQ_DISTRICT.NEXTVAL,'SAN JUAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(113,SEQ_DISTRICT.NEXTVAL,'CINCO ESQUINAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(113,SEQ_DISTRICT.NEXTVAL,'ANSELMO LLORENTE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(113,SEQ_DISTRICT.NEXTVAL,'LEON XIII',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(113,SEQ_DISTRICT.NEXTVAL,'COLIMA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,114,'MORAVIA');
--DISTRITOS SAN JOSE / MORAVIA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(114,SEQ_DISTRICT.NEXTVAL,'SAN VICENTE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(114,SEQ_DISTRICT.NEXTVAL,'SAN GERONIMO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(114,SEQ_DISTRICT.NEXTVAL,'TRINIDAD',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,115,'MONTES DE OCA');
--DISTRITOS SAN JOSE / MONTES DE OCA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(115,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(115,SEQ_DISTRICT.NEXTVAL,'SABANILLA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(115,SEQ_DISTRICT.NEXTVAL,'MERCEDES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(115,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,116,'TURRUBARES');
--DISTRITOS SAN JOSE / TURRUBARES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(116,SEQ_DISTRICT.NEXTVAL,'SAN PABLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(116,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(116,SEQ_DISTRICT.NEXTVAL,'SAN JUAN DE MATA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(116,SEQ_DISTRICT.NEXTVAL,'SAN LUIS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(116,SEQ_DISTRICT.NEXTVAL,'CARANA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,117,'DOTA');
--DISTRITOS SAN JOSE / DOTA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(117,SEQ_DISTRICT.NEXTVAL,'SANTA MARIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(117,SEQ_DISTRICT.NEXTVAL,'JARDIN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(117,SEQ_DISTRICT.NEXTVAL,'COPEY',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,118,'CURRIDABAT');
--DISTRITOS SAN JOSE / CURRIDABAT--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(118,SEQ_DISTRICT.NEXTVAL,'CURRIDABAT',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(118,SEQ_DISTRICT.NEXTVAL,'GRANADILLA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(118,SEQ_DISTRICT.NEXTVAL,'SANCHEZ',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(118,SEQ_DISTRICT.NEXTVAL,'TIRRASES',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,119,'PEREZ ZELEDON');
--DISTRITOS SAN JOSE / PEREZ ZELEDON--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO DEL GENERA;',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'GENERAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'DANIEL FLORES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'RIVAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'PLATANARES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'PEJIBAYE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'CAJON',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'BARU',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'RIO NUEVO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(119,SEQ_DISTRICT.NEXTVAL,'PARAMO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,120,'LEON CORTES');
--DISTRITOS SAN JOSE / LEON CORTES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SAN PABLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SAN ANDRES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(120,SEQ_DISTRICT.NEXTVAL,'LLANO BONITO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SANTA CRUZ',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(120,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO',0.0,0.0);




--                                      ************************
--                                      |       ALAJUELA       |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,201,'ALAJUELA');
--DISTRITOS ALAJUELA / ALAJUELA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'ALAJUELA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SAN JOSE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'CARRIZAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'GUACIMA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SABANILLA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'RIO SEGUNDO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'DESAMPARADOS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'TURRUCARES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'TAMBOR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'GARITA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(201,SEQ_DISTRICT.NEXTVAL,'SARAPIQUI',0.0,0.0);

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,202,'SAN RAMON');
--DISTRITOS ALAJUELA / SAN RAMON--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SAN RAMON',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SANTIAGO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SAN JUAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'PIEDADES NORTE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'PIEDADES SUR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'ANGELES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'ALAFARO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'VOLIO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'CONCEPCION',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'ZAPOTAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(202,SEQ_DISTRICT.NEXTVAL,'PEÑAS BLANCAS',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,203,'GRECIA');
--DISTRITOS ALAJUELA / GRECIA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(203,SEQ_DISTRICT.NEXTVAL,'GRECIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(203,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(203,SEQ_DISTRICT.NEXTVAL,'SAN JOSE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(203,SEQ_DISTRICT.NEXTVAL,'SAN ROQUE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(203,SEQ_DISTRICT.NEXTVAL,'TACARES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(203,SEQ_DISTRICT.NEXTVAL,'RIO CUARTO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(203,SEQ_DISTRICT.NEXTVAL,'PUENTE DE PIEDRA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(203,SEQ_DISTRICT.NEXTVAL,'BOLIVAR',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,204,'SAN MATEO');
--DISTRITOS ALAJUELA / SAN MATEO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(204,SEQ_DISTRICT.NEXTVAL,'SAN MATEO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(204,SEQ_DISTRICT.NEXTVAL,'DESMONTES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(204,SEQ_DISTRICT.NEXTVAL,'JESUS MARIA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,205,'ATENAS');
--DISTRITOS ALAJUELA / ATENAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(205,SEQ_DISTRICT.NEXTVAL,'ATENAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(205,SEQ_DISTRICT.NEXTVAL,'JESUS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(205,SEQ_DISTRICT.NEXTVAL,'MERCEDES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(205,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(205,SEQ_DISTRICT.NEXTVAL,'CONCEPCION',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(205,SEQ_DISTRICT.NEXTVAL,'SAN JOSE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(205,SEQ_DISTRICT.NEXTVAL,'SANTA EULALIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(205,SEQ_DISTRICT.NEXTVAL,'ESCOBAL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,206,'NARANJO');
--DISTRITOS ALAJUELA / NARANJO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(206,SEQ_DISTRICT.NEXTVAL,'NARANJO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(206,SEQ_DISTRICT.NEXTVAL,'SAN MIGUEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(206,SEQ_DISTRICT.NEXTVAL,'SAN JOSE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(206,SEQ_DISTRICT.NEXTVAL,'CIRRI SUR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(206,SEQ_DISTRICT.NEXTVAL,'SAN JERONIMO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(206,SEQ_DISTRICT.NEXTVAL,'SAN JUAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(206,SEQ_DISTRICT.NEXTVAL,'ROSARIO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,207,'PALMARES');
--DISTRITOS ALAJUELA / PALMARES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(207,SEQ_DISTRICT.NEXTVAL,'PALMARES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(207,SEQ_DISTRICT.NEXTVAL,'ZARAGOZA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(207,SEQ_DISTRICT.NEXTVAL,'BUENOS AIRES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(207,SEQ_DISTRICT.NEXTVAL,'SANTIAGO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(207,SEQ_DISTRICT.NEXTVAL,'CANDELARIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(207,SEQ_DISTRICT.NEXTVAL,'ESQUIPULAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(207,SEQ_DISTRICT.NEXTVAL,'GRANJA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,208,'POAS');
--DISTRITOS ALAJUELA / POAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(208,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(208,SEQ_DISTRICT.NEXTVAL,'SAN JUAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(208,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(208,SEQ_DISTRICT.NEXTVAL,'CARRILLOS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(208,SEQ_DISTRICT.NEXTVAL,'SABANA REDONDA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,209,'OROTINA');
--DISTRITOS ALAJUELA / OROTINA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(209,SEQ_DISTRICT.NEXTVAL,'OROTINA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(209,SEQ_DISTRICT.NEXTVAL,'MASTATE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(209,SEQ_DISTRICT.NEXTVAL,'HACIENDA VIEJA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(209,SEQ_DISTRICT.NEXTVAL,'COYOLAR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(209,SEQ_DISTRICT.NEXTVAL,'CEIBA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,210,'SAN CARLOS');
--DISTRITOS ALAJUELA / SAN CARLOS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'QUESADA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'FLORENCIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'BUENAVISTA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'AGUAS ZARCAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'VENECIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'PITAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'FORTUNA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'TIGRA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'PALMERA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'VENADO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'CUTRIS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(210,SEQ_DISTRICT.NEXTVAL,'MONTERREY',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,211,'ALFARO RUIZ');
--DISTRITOS ALAJUELA / ALFARO RUIZ--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(211,SEQ_DISTRICT.NEXTVAL,'ZARCERO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(211,SEQ_DISTRICT.NEXTVAL,'LAGUNA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(211,SEQ_DISTRICT.NEXTVAL,'TAPEZCO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(211,SEQ_DISTRICT.NEXTVAL,'GUADALUPE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(211,SEQ_DISTRICT.NEXTVAL,'PALMIRA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(211,SEQ_DISTRICT.NEXTVAL,'ZAPOTE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(211,SEQ_DISTRICT.NEXTVAL,'BRISAS',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,212,'VALVERDE VEGA');
--DISTRITOS ALAJUELA / VALVERDE VEGA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(212,SEQ_DISTRICT.NEXTVAL,'SARCHI NORTE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(212,SEQ_DISTRICT.NEXTVAL,'SARCHI SUR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(212,SEQ_DISTRICT.NEXTVAL,'TORO AMARILLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(212,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(212,SEQ_DISTRICT.NEXTVAL,'RODRIGUEZ',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,213,'UPALA');
--DISTRITOS ALAJUELA / UPALA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(213,SEQ_DISTRICT.NEXTVAL,'UPALA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(213,SEQ_DISTRICT.NEXTVAL,'AGUAS CLARAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(213,SEQ_DISTRICT.NEXTVAL,'SAN JOSE(PIZOTE)',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(213,SEQ_DISTRICT.NEXTVAL,'BIJAGUA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(213,SEQ_DISTRICT.NEXTVAL,'DELICIAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(213,SEQ_DISTRICT.NEXTVAL,'DOS RIOS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(213,SEQ_DISTRICT.NEXTVAL,'YOLIYLLAL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,214,'LOS CHILES');
--DISTRITOS ALAJUELA / LOS CHILES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(214,SEQ_DISTRICT.NEXTVAL,'LOS CHILES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(214,SEQ_DISTRICT.NEXTVAL,'CAÑO NEGRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(214,SEQ_DISTRICT.NEXTVAL,'EL AMPARO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(214,SEQ_DISTRICT.NEXTVAL,'SAN JORGE',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(2,215,'GUATUSO');
--DISTRITOS ALAJUELA / GUATUSO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(215,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(215,SEQ_DISTRICT.NEXTVAL,'BUENA VISTA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(215,SEQ_DISTRICT.NEXTVAL,'COTE',0.0,0.0);




--                                      ************************
--                                      |       CARTAGO        |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,301,'CARTAGO');
--DISTRITOS CARTAGO / CARTAGO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'ORIENTAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'OCCIDENTAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'CARMEN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'SAN NICOLAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'AGUACALIENTE (SAN FRANCISCO)',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'GUADALUPE (ARENILLA)',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'CORRALILLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'TIERRA BLANCA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'DULCE NOMBRE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'LLANO GRANDE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(301,SEQ_DISTRICT.NEXTVAL,'QUEBRADILLA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,302,'PARAISO');
--DISTRITOS CARTAGO / PARAISO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(302,SEQ_DISTRICT.NEXTVAL,'PARAISO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(302,SEQ_DISTRICT.NEXTVAL,'SANTIAGO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(302,SEQ_DISTRICT.NEXTVAL,'OROSI',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(302,SEQ_DISTRICT.NEXTVAL,'CACHI',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(302,SEQ_DISTRICT.NEXTVAL,'LLANOS DE SANTA LUCIA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,303,'LA UNION');
--DISTRITOS CARTAGO / LA UNION--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(303,SEQ_DISTRICT.NEXTVAL,'TRES RIOS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(303,SEQ_DISTRICT.NEXTVAL,'SAN DIEGO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(303,SEQ_DISTRICT.NEXTVAL,'SAN JUAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(303,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(303,SEQ_DISTRICT.NEXTVAL,'CONCEPCION',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(303,SEQ_DISTRICT.NEXTVAL,'DULCE NOMBRE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(303,SEQ_DISTRICT.NEXTVAL,'SAN RAMON',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(303,SEQ_DISTRICT.NEXTVAL,'RIO AZUL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,304,'JIMENEZ');
--DISTRITOS CARTAGO / JIMENEZ--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(304,SEQ_DISTRICT.NEXTVAL,'JUAN VIÑAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(304,SEQ_DISTRICT.NEXTVAL,'TUCURRIQUE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(304,SEQ_DISTRICT.NEXTVAL,'PEJIBAYE',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,305,'TURRIALBA');
--DISTRITOS CARTAGO / TURRIALBA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'TURRIALBA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'LA SUIZA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'PERALTA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'SANTA CRUZ',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'SANTA TERESITA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'PAVONES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'TUIS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'TAYUTIC',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'SANTA ROSA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'TRES EQUIS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'LA ISABEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(305,SEQ_DISTRICT.NEXTVAL,'CHIRRIPO',0.0,0.0);

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,306,'ALVARADO');
--DISTRITOS CARTAGO / ALVARADO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(306,SEQ_DISTRICT.NEXTVAL,'PACAYAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(306,SEQ_DISTRICT.NEXTVAL,'CERVANTES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(306,SEQ_DISTRICT.NEXTVAL,'CAPELLADES',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,307,'OREAMUNO');
--DISTRITOS CARTAGO / OREAMUNO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(307,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(307,SEQ_DISTRICT.NEXTVAL,'COTE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(307,SEQ_DISTRICT.NEXTVAL,'POTRERO CERRADO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(307,SEQ_DISTRICT.NEXTVAL,'CIPRESES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(307,SEQ_DISTRICT.NEXTVAL,'SANTA ROSA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(3,308,'EL GUARCO');
--DISTRITOS CARTAGO / EL GUARCO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(308,SEQ_DISTRICT.NEXTVAL,'TEJAR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(308,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(308,SEQ_DISTRICT.NEXTVAL,'TOBOSI',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(308,SEQ_DISTRICT.NEXTVAL,'PATIO DE AGUA',0.0,0.0);




--                                      ************************
--                                      |       HEREDIA        |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,401,'HEREDIA');
--DISTRITOS HEREDIA / HEREDIA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(401,SEQ_DISTRICT.NEXTVAL,'HEREDIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(401,SEQ_DISTRICT.NEXTVAL,'MERCEDES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(401,SEQ_DISTRICT.NEXTVAL,'SAN FRANCISCO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(401,SEQ_DISTRICT.NEXTVAL,'ULLOA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(401,SEQ_DISTRICT.NEXTVAL,'VARABLANCA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,402,'BARVA');
--DISTRITOS HEREDIA / BARVA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(402,SEQ_DISTRICT.NEXTVAL,'BARVA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SAN PABLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SAN ROQUE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SANTA LUCIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(402,SEQ_DISTRICT.NEXTVAL,'SAN JOSE DE LA MONTAÑA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,403,'SANTO DOMINGO');
--DISTRITOS HEREDIA / SANTO DOMINGO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SANTO DOMINGO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SAN VICENTE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SAN MIGUEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(403,SEQ_DISTRICT.NEXTVAL,'PARACITO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SANTO TOMAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(403,SEQ_DISTRICT.NEXTVAL,'SANTA ROSA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(403,SEQ_DISTRICT.NEXTVAL,'TURES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(403,SEQ_DISTRICT.NEXTVAL,'PARA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,404,'SANTA BARBARA');
--DISTRITOS HEREDIA / SANTA BARBARA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(404,SEQ_DISTRICT.NEXTVAL,'SANTA BARBARA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(404,SEQ_DISTRICT.NEXTVAL,'SAN PEDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(404,SEQ_DISTRICT.NEXTVAL,'SAN JUAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(404,SEQ_DISTRICT.NEXTVAL,'JESUS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(404,SEQ_DISTRICT.NEXTVAL,'SANTO DOMINGO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(404,SEQ_DISTRICT.NEXTVAL,'PURABA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,405,'SAN RAFAEL');
--DISTRITOS HEREDIA / SAN RAFAEL--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(405,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(405,SEQ_DISTRICT.NEXTVAL,'SAN JOSECITO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(405,SEQ_DISTRICT.NEXTVAL,'SANTIAGO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(405,SEQ_DISTRICT.NEXTVAL,'ANGELES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(405,SEQ_DISTRICT.NEXTVAL,'CONCEPCION',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,406,'SAN ISIDRO');
--DISTRITOS HEREDIA / SAN ISIDRO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(406,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(406,SEQ_DISTRICT.NEXTVAL,'SAN JOSE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(406,SEQ_DISTRICT.NEXTVAL,'CONCEPCION',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(406,SEQ_DISTRICT.NEXTVAL,'SAN FRANCISCO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,407,'BELEN');
--DISTRITOS HEREDIA / BELEN--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(407,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(407,SEQ_DISTRICT.NEXTVAL,'RIBERA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(407,SEQ_DISTRICT.NEXTVAL,'ASUNCION',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,408,'SAN JOAQUIN DE FLORES');
--DISTRITOS HEREDIA / SAN JOAQUIN DE FLORES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(408,SEQ_DISTRICT.NEXTVAL,'SAN JOAQUIN DE FLORES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(408,SEQ_DISTRICT.NEXTVAL,'BARRANTES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(408,SEQ_DISTRICT.NEXTVAL,'LLORENTE',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,409,'SAN PABLO');
--DISTRITOS HEREDIA / SAN PABLO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(409,SEQ_DISTRICT.NEXTVAL,'SAN PABLO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(4,410,'SARAPIQUI');
--DISTRITOS HEREDIA / SARAPIQUI--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(410,SEQ_DISTRICT.NEXTVAL,'PUERTO VIEJO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(410,SEQ_DISTRICT.NEXTVAL,'LA VIRGEN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(410,SEQ_DISTRICT.NEXTVAL,'HORQUETAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(410,SEQ_DISTRICT.NEXTVAL,'LLANURAS DEL GASPAR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(410,SEQ_DISTRICT.NEXTVAL,'CUREÑA',0.0,0.0);




--                                      ************************
--                                      |      GUANACASTE      |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,501,'LIBERIA');
--DISTRITOS GUANACASTE / LIBERIA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(501,SEQ_DISTRICT.NEXTVAL,'LIBERIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(501,SEQ_DISTRICT.NEXTVAL,'CAÑAS DULCES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(501,SEQ_DISTRICT.NEXTVAL,'MAYORGA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(501,SEQ_DISTRICT.NEXTVAL,'NACASCOLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(501,SEQ_DISTRICT.NEXTVAL,'CURUBANDE',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,502,'NICOYA');
--DISTRITOS GUANACASTE / NICOYA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(502,SEQ_DISTRICT.NEXTVAL,'NICOYA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(502,SEQ_DISTRICT.NEXTVAL,'MANSION',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(502,SEQ_DISTRICT.NEXTVAL,'SAN ANTONIO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(502,SEQ_DISTRICT.NEXTVAL,'QUEBRADA HONDA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(502,SEQ_DISTRICT.NEXTVAL,'SAMARA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(502,SEQ_DISTRICT.NEXTVAL,'NOSARA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(502,SEQ_DISTRICT.NEXTVAL,'BELEN DE NOSARITA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,503,'SANTA CRUZ');
--DISTRITOS GUANACASTE / SANTA CRUZ--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(503,SEQ_DISTRICT.NEXTVAL,'SANTA CRUZ',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(503,SEQ_DISTRICT.NEXTVAL,'BOLSON',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(503,SEQ_DISTRICT.NEXTVAL,'VEINTISIETE DE ABRIL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(503,SEQ_DISTRICT.NEXTVAL,'TEMPATE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(503,SEQ_DISTRICT.NEXTVAL,'CARTAGENA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(503,SEQ_DISTRICT.NEXTVAL,'CUAJINIQUIL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(503,SEQ_DISTRICT.NEXTVAL,'DIRIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(503,SEQ_DISTRICT.NEXTVAL,'CABO VELAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(503,SEQ_DISTRICT.NEXTVAL,'TAMARINDO',0.0,0.0);

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,504,'BAGACES');
--DISTRITOS GUANACASTE / VAGACES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(504,SEQ_DISTRICT.NEXTVAL,'BAGACES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(504,SEQ_DISTRICT.NEXTVAL,'FORTUNA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(504,SEQ_DISTRICT.NEXTVAL,'MOGOTE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(504,SEQ_DISTRICT.NEXTVAL,'RIO NARANJO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,505,'CARRILLO');
--DISTRITOS GUANACASTE / CARRILLO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(505,SEQ_DISTRICT.NEXTVAL,'FILADELFIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(505,SEQ_DISTRICT.NEXTVAL,'PALMIRA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(505,SEQ_DISTRICT.NEXTVAL,'SARDINAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(505,SEQ_DISTRICT.NEXTVAL,'BELEN',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,506,'CAÑAS');
--DISTRITOS GUANACASTE / CAÑAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(506,SEQ_DISTRICT.NEXTVAL,'CAÑAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(506,SEQ_DISTRICT.NEXTVAL,'PALMIRA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(506,SEQ_DISTRICT.NEXTVAL,'SAN MIGUEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(506,SEQ_DISTRICT.NEXTVAL,'BEBEDERO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(506,SEQ_DISTRICT.NEXTVAL,'POROZAL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,507,'ABANGARES');
--DISTRITOS GUANACASTE / ABANGARES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(507,SEQ_DISTRICT.NEXTVAL,'JUNTAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(507,SEQ_DISTRICT.NEXTVAL,'SIERRA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(507,SEQ_DISTRICT.NEXTVAL,'SAN JUAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(507,SEQ_DISTRICT.NEXTVAL,'COLORADO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,508,'TILARAN');
--DISTRITOS GUANACASTE / TILARAN--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(508,SEQ_DISTRICT.NEXTVAL,'TILARAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(508,SEQ_DISTRICT.NEXTVAL,'QUEBRADA GRANDE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(508,SEQ_DISTRICT.NEXTVAL,'TRONADORA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(508,SEQ_DISTRICT.NEXTVAL,'SANTA ROSA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(508,SEQ_DISTRICT.NEXTVAL,'LIBANO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(508,SEQ_DISTRICT.NEXTVAL,'TIERRAS MORENAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(508,SEQ_DISTRICT.NEXTVAL,'ARENAL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,509,'NANDAYURE');
--DISTRITOS GUANACASTE / NANDAYURE--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(509,SEQ_DISTRICT.NEXTVAL,'CARMONA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(509,SEQ_DISTRICT.NEXTVAL,'SANTA RITA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(509,SEQ_DISTRICT.NEXTVAL,'ZAPOTAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(509,SEQ_DISTRICT.NEXTVAL,'SAN PABLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(509,SEQ_DISTRICT.NEXTVAL,'PORVENIR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(509,SEQ_DISTRICT.NEXTVAL,'BEJUCO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,510,'LA CRUZ');
--DISTRITOS GUANACASTE / LA CRUZ--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(510,SEQ_DISTRICT.NEXTVAL,'LA CRUZ',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(510,SEQ_DISTRICT.NEXTVAL,'SANTA CECILIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(510,SEQ_DISTRICT.NEXTVAL,'GARITA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(510,SEQ_DISTRICT.NEXTVAL,'SANTA ELENA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(5,511,'HOJANCHA');
--DISTRITOS GUANACASTE / HOJANCHA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(511,SEQ_DISTRICT.NEXTVAL,'HOJANCHA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(511,SEQ_DISTRICT.NEXTVAL,'MONTE ROMO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(511,SEQ_DISTRICT.NEXTVAL,'PUERTO CARRILLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(511,SEQ_DISTRICT.NEXTVAL,'HUACAS',0.0,0.0);




--                                      ************************
--                                      |      PUNTARENAS      |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,601,'PUNTARENAS');
--DISTRITOS PUNTARENAS / PUNTARENAS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'PUNTARENAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'PITAHAYA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'CHOMES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'LEPANTO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'PAQUERA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'MANZANILLO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'GUACIMAL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'BARRANCA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'MONTE VERDE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'ISLA DEL COCO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'COBANO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'CHACARICA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'CHIRA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'ACAPULCO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'EL ROBLE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(601,SEQ_DISTRICT.NEXTVAL,'ARANCIBIA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,602,'ESPARZA');
--DISTRITOS PUNTARENAS / ESPARZA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(602,SEQ_DISTRICT.NEXTVAL,'ESPIRITU SANTO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(602,SEQ_DISTRICT.NEXTVAL,'SAN JUAN GRANDE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(602,SEQ_DISTRICT.NEXTVAL,'MACACONA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(602,SEQ_DISTRICT.NEXTVAL,'SAN RAFAEL',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(602,SEQ_DISTRICT.NEXTVAL,'SAN GERONIMO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,603,'BUENOS AIRES');
--DISTRITOS PUNTARENAS / BUANOS AIRES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(603,SEQ_DISTRICT.NEXTVAL,'BUENOS AIRES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(603,SEQ_DISTRICT.NEXTVAL,'VOLCAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(603,SEQ_DISTRICT.NEXTVAL,'POTRERO GRANDE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(603,SEQ_DISTRICT.NEXTVAL,'BORUCA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(603,SEQ_DISTRICT.NEXTVAL,'PILAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(603,SEQ_DISTRICT.NEXTVAL,'COLINAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(603,SEQ_DISTRICT.NEXTVAL,'CHANGENA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(603,SEQ_DISTRICT.NEXTVAL,'BRIOLLEY',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(603,SEQ_DISTRICT.NEXTVAL,'BRUNKA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,604,'MONTES DE ORO');
--DISTRITOS PUNTARENAS / MONTES DE ORO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(604,SEQ_DISTRICT.NEXTVAL,'MIRAMAR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(604,SEQ_DISTRICT.NEXTVAL,'UNION',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(604,SEQ_DISTRICT.NEXTVAL,'SAN ISIDRO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,605,'OSA');
--DISTRITOS PUNTARENAS / OSA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(605,SEQ_DISTRICT.NEXTVAL,'PUERTO CORTES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(605,SEQ_DISTRICT.NEXTVAL,'PALMAR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(605,SEQ_DISTRICT.NEXTVAL,'SIERPE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(605,SEQ_DISTRICT.NEXTVAL,'BAHIA BALLENA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(605,SEQ_DISTRICT.NEXTVAL,'PIEDRAS BLANCAS',0.0,0.0);

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,606,'AGUIRRE');
--DISTRITOS PUNTARENAS / AGUIRRE--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(606,SEQ_DISTRICT.NEXTVAL,'QUEPOS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(606,SEQ_DISTRICT.NEXTVAL,'SAVEGRE',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(606,SEQ_DISTRICT.NEXTVAL,'NARANJITO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,607,'GOLFITO');
--DISTRITOS PUNTARENAS / GOLFITO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(607,SEQ_DISTRICT.NEXTVAL,'GOLFITO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(607,SEQ_DISTRICT.NEXTVAL,'PUERTO JIMENEZ',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(607,SEQ_DISTRICT.NEXTVAL,'GUAYCARA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(607,SEQ_DISTRICT.NEXTVAL,'PAVON',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,608,'COTO BRUS');
--DISTRITOS PUNTARENAS / COTO BRUS--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(608,SEQ_DISTRICT.NEXTVAL,'SAN VITO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(608,SEQ_DISTRICT.NEXTVAL,'SABALITO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(608,SEQ_DISTRICT.NEXTVAL,'AGUABUENA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(608,SEQ_DISTRICT.NEXTVAL,'LIMONCITO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(608,SEQ_DISTRICT.NEXTVAL,'PITTIER',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,609,'PARRITA');
--DISTRITOS PUNTARENAS / PARRITA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(609,SEQ_DISTRICT.NEXTVAL,'PARRITA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,610,'CORREDORES');
--DISTRITOS PUNTARENAS / CORREDORES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(610,SEQ_DISTRICT.NEXTVAL,'CORREDOR',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(610,SEQ_DISTRICT.NEXTVAL,'LA CUESTA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(610,SEQ_DISTRICT.NEXTVAL,'CANOAS',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(610,SEQ_DISTRICT.NEXTVAL,'LAUREL',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(6,611,'GARABITO');
--DISTRITOS PUNTARENAS / GARABITO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(611,SEQ_DISTRICT.NEXTVAL,'JACO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(611,SEQ_DISTRICT.NEXTVAL,'TARCOLES',0.0,0.0);




--                                      ************************
--                                      |        LIMON         |
--                                      ************************

INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,701,'LIMON');
--DISTRITOS LIMON / LIMON--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(701,SEQ_DISTRICT.NEXTVAL,'LIMON',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(701,SEQ_DISTRICT.NEXTVAL,'VALLE LA ESTRELLA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(701,SEQ_DISTRICT.NEXTVAL,'RIO BLANCO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(701,SEQ_DISTRICT.NEXTVAL,'MATAMA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,702,'POCOCI');
--DISTRITOS LIMON / POCOCI--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(702,SEQ_DISTRICT.NEXTVAL,'GUAPILES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(702,SEQ_DISTRICT.NEXTVAL,'JIMENEZ',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(702,SEQ_DISTRICT.NEXTVAL,'RITA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(702,SEQ_DISTRICT.NEXTVAL,'ROXANA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(702,SEQ_DISTRICT.NEXTVAL,'CARIARI',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(702,SEQ_DISTRICT.NEXTVAL,'COLORADO',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,703,'SIQUIRRES');
--DISTRITOS LIMON / SIQUIRRES--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(703,SEQ_DISTRICT.NEXTVAL,'SIQUIRRES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(703,SEQ_DISTRICT.NEXTVAL,'PACUARITO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(703,SEQ_DISTRICT.NEXTVAL,'FLORIDA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(703,SEQ_DISTRICT.NEXTVAL,'GERMANIA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(703,SEQ_DISTRICT.NEXTVAL,'CAIRO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(703,SEQ_DISTRICT.NEXTVAL,'ALEGRIA',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,704,'TALAMANCA');
--DISTRITOS LIMON / TALAMANCA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(704,SEQ_DISTRICT.NEXTVAL,'BRATSI',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(704,SEQ_DISTRICT.NEXTVAL,'SIXAOLA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(704,SEQ_DISTRICT.NEXTVAL,'CAHUITA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(704,SEQ_DISTRICT.NEXTVAL,'TELIRE',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,705,'MATINA');
--DISTRITOS LIMON / MATINA--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(705,SEQ_DISTRICT.NEXTVAL,'MATINA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(705,SEQ_DISTRICT.NEXTVAL,'BATTAN',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(705,SEQ_DISTRICT.NEXTVAL,'CARRANDI',0.0,0.0);


INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(7,706,'GUACIMO');
--DISTRITOS LIMON / GUACIMO--
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(706,SEQ_DISTRICT.NEXTVAL,'GUACIMO',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(706,SEQ_DISTRICT.NEXTVAL,'MERDECES',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(706,SEQ_DISTRICT.NEXTVAL,'POCORA',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(706,SEQ_DISTRICT.NEXTVAL,'RIO JIMENEZ',0.0,0.0);
INSERT INTO DISTRICT(CANTON_ID,DISTRICT_ID,DISTRICT_NAME,LATITUDE,LONGITUDE) VALUES(706,SEQ_DISTRICT.NEXTVAL,'DUACARI',0.0,0.0);

COMMIT;