--
--INSERT PROVINCES FROM COSTA RICA
--
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 1, 'San Jose');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 2, 'Alajuela');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 3, 'Cartago');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 4, 'Heredia');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 5, 'Guanacaste');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 6, 'Puntarenas');
INSERT INTO PROVINCE(COUNTRY_ID,PROVINCE_ID,PROVINCE_NAME) VALUES (46, 7, 'Limon');
--
--INSERT CANTONS FROM SAN JOSE
--
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,1,'SAN JOSE');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,2,'ESCAZU');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,3,'DESAMPARADOS');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,4,'PURISCAL');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,5,'TARRAZU');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,6,'ASERRI');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,7,'MORA');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,8,'GOICOCHEA');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,9,'SANTA ANA');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,10,'ALAJUELITA');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,11,'VAZQUEZ DE CORONADO');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,12,'ACOSTA');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,13,'TIBAS');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,14,'MORAVIA');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,15,'MONTES DE OCA');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,16,'TURRUBARES');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,17,'DOTA');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,18,'CURRIDABAT');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,19,'PEREZ ZELEDON');
INSERT INTO CANTON(PROVINCE_ID,CANTON_ID,CANTON_NAME) VALUES(1,20,'LEON CORTES');
