CREATE USER p_user
       IDENTIFIED by password
       DEFAULT TABLESPACE PROYECTO1
       QUOTA 10M ON PROYECTO1
       TEMPORARY TABLESPACE temp
       QUOTA 5M ON system;

GRANT CONNECT TO p_user;
GRANT RESOURCE TO p_user;
GRANT CREATE ANY INDEX TO p_user;
GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO p_user;
GRANT UNLIMITED TABLESPACE TO p_user;
GRANT ALTER ANY INDEX TO p_user;
GRANT ALTER ANY SEQUENCE TO p_user;
GRANT ALTER ANY TABLE TO p_user;
GRANT ALTER ANY TRIGGER TO p_user;
GRANT CREATE ANY INDEX TO p_user;
GRANT CREATE ANY SEQUENCE TO p_user;
GRANT CREATE ANY SYNONYM TO p_user;
GRANT CREATE ANY TABLE TO p_user;
GRANT CREATE ANY TRIGGER TO p_user;
GRANT CREATE ANY VIEW TO p_user;
GRANT CREATE PROCEDURE TO p_user;
GRANT CREATE PUBLIC SYNONYM TO p_user;
GRANT CREATE TRIGGER TO p_user;
GRANT CREATE VIEW TO p_user;
GRANT DELETE ANY TABLE TO p_user;
GRANT DROP ANY INDEX TO p_user;
GRANT DROP ANY SEQUENCE TO p_user;
GRANT DROP ANY TABLE TO p_user;
GRANT DROP ANY TRIGGER TO p_user;
GRANT DROP ANY VIEW TO p_user;
GRANT INSERT ANY TABLE TO p_user;
GRANT QUERY REWRITE TO p_user;
GRANT SELECT ANY TABLE TO p_user;
GRANT UNLIMITED TABLESPACE TO p_user;
GRANT CREATE PROCEDURE TO p_user;