--
--ADD PRIMARY KEYS
--
ALTER TABLE ANML_CLASS
      ADD CONSTRAINT CLASS_PK PRIMARY KEY(CLASS_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE ANML_ORDER
      ADD CONSTRAINT ORDER_PK PRIMARY KEY(ORDER_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE ANML_SUBORDER
      ADD CONSTRAINT SUBORDER_PK PRIMARY KEY(SUBORDER_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE ANML_FAMILY
      ADD CONSTRAINT FAMILY_PK PRIMARY KEY(FAMILY_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE ANML_GENDER
      ADD CONSTRAINT GENDER_PK PRIMARY KEY(GENDER_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE ANML_SPECIE
      ADD CONSTRAINT SPECIE_PK PRIMARY KEY(SPECIE_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE SIGHT
      ADD CONSTRAINT SIGHT_PK PRIMARY KEY(SIGHT_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE SYSTEM_USER
      ADD CONSTRAINT USER_PK PRIMARY KEY(USER_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE BINNACLE
      ADD CONSTRAINT BINNACLE_PK PRIMARY KEY(BINNACLE_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE DISTRICT
      ADD CONSTRAINT DISTRICT_PK PRIMARY KEY(DISTRICT_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE CANTON
      ADD CONSTRAINT CANTON_PK PRIMARY KEY(CANTON_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE PROVINCE
      ADD CONSTRAINT PROVINCE_PK PRIMARY KEY(PROVINCE_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE COUNTRY
      ADD CONSTRAINT COUNTRY_PK PRIMARY KEY(COUNTRY_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE CONTINENT
      ADD CONSTRAINT CONTINENT_PK PRIMARY KEY(CONTINENT_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
ALTER TABLE SYSTEM_PARAMETERS
      ADD CONSTRAINT SP_PK PRIMARY KEY(P_ID)
      USING INDEX
      TABLESPACE ID_PROYECTO1 PCTFREE 20
      STORAGE(INITIAL 10K NEXT 10K PCTINCREASE 0);
--
--ADD FOREIGN KEYS
--
--***|ANIMALS|***--
ALTER TABLE ANML_ORDER ADD FOREIGN KEY (CLASS_ID) REFERENCES ANML_CLASS(CLASS_ID); 
ALTER TABLE ANML_SUBORDER ADD FOREIGN KEY (ORDER_ID) REFERENCES ANML_ORDER(ORDER_ID);
ALTER TABLE ANML_FAMILY ADD FOREIGN KEY (SUBORDER_ID) REFERENCES ANML_SUBORDER(SUBORDER_ID);
ALTER TABLE ANML_GENDER ADD FOREIGN KEY (FAMILY_ID) REFERENCES ANML_FAMILY(FAMILY_ID);
ALTER TABLE ANML_SPECIE ADD FOREIGN KEY (GENDER_ID) REFERENCES ANML_GENDER(GENDER_ID);
--***|PLACES|***--
ALTER TABLE COUNTRY ADD FOREIGN KEY (CONTINENT_ID) REFERENCES CONTINENT(CONTINENT_ID);
ALTER TABLE PROVINCE ADD FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID);
ALTER TABLE CANTON ADD FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCE(PROVINCE_ID);
ALTER TABLE DISTRICT ADD FOREIGN KEY (CANTON_ID) REFERENCES CANTON(CANTON_ID);
--***|OTHERS|***--
ALTER TABLE SIGHT ADD FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USER(USER_ID);
ALTER TABLE SIGHT ADD FOREIGN KEY (SPECIE_ID) REFERENCES ANML_SPECIE(SPECIE_ID);
ALTER TABLE SIGHT ADD FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICT(DISTRICT_ID);
ALTER TABLE RATEXUSER ADD FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USER(USER_ID);
ALTER TABLE RATEXUSER ADD FOREIGN KEY (SIGHT_ID) REFERENCES SIGHT(SIGHT_ID);
ALTER TABLE BINNACLE ADD FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USER(USER_ID);
ALTER TABLE ORNITHOLOGIST ADD FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USER(USER_ID);
ALTER TABLE AMATEUR ADD FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USER(USER_ID);

