ALTER TABLE DISTRICT
  DROP COLUMN LONGITUDE;
ALTER TABLE DISTRICT
  DROP COLUMN LATITUDE;
  
ALTER TABLE SIGHT
  ADD LONGITUDE NUMBER(20,20) CONSTRAINT SIGHT_LONGITUDE NOT NULL;
ALTER TABLE SIGHT
  ADD LATITUDE NUMBER(20,20) CONSTRAINT SIGHT_LATITUDE NOT NULL;