--ALTER TABLE DISTRICT DROP COLUMN LONGITUDE;
--ALTER TABLE SIGHT ADD LATITUDE NUMBER(20,20) CONSTRAINT SIGHT_LATITUDE NOT NULL;

--ALTER TABLE SIGHT MODIFY LATITUDE NUMBER(20,10);
--ALTER TABLE SIGHT MODIFY LONGITUDE NUMBER(20,10);

SELECT SIGHT.SIGHT_ID,SIGHT.DATE_CREATION, SIGHT.IMAGE_URL, SYSTEM_USER.USER_NICKNAME, DISTRICT.DISTRICT_NAME, CANTON.CANTON_NAME, PROVINCE.PROVINCE_NAME, COUNTRY.COUNTRY_NAME
    FROM SIGHT 
    INNER JOIN SYSTEM_USER
    ON SYSTEM_USER.USER_ID = SIGHT.USER_ID
    INNER JOIN DISTRICT
    ON DISTRICT.DISTRICT_ID = SIGHT.DISTRICT_ID
    INNER JOIN CANTON
    ON DISTRICT.CANTON_ID = CANTON.CANTON_ID
    INNER JOIN PROVINCE
    ON CANTON.PROVINCE_ID = PROVINCE.PROVINCE_ID
    INNER JOIN COUNTRY
    ON PROVINCE.COUNTRY_ID = COUNTRY.COUNTRY_ID;
    
    SELECT * FROM ANML_SPECIE;
    
SELECT SIGHT.SIGHT_ID, SIGHT.LATITUDE, SIGHT.LONGITUDE, SIGHT.IMAGE_URL, SYSTEM_USER.USER_NICKNAME , ANML_SPECIE.SPECIE_NAME
 FROM SIGHT

INNER JOIN SYSTEM_USER
ON SYSTEM_USER.USER_ID = SIGH   T.USER_ID

INNER JOIN DISTRICT
ON SIGHT.DISTRICT_ID = DISTRICT.DISTRICT_ID
INNER JOIN CANTON
ON DISTRICT.CANTON_ID = CANTON.CANTON_ID
INNER JOIN PROVINCE
ON CANTON.PROVINCE_ID = PROVINCE.PROVINCE_ID

INNER JOIN ANML_SPECIE
ON SIGHT.SPECIE_ID = ANML_SPECIE.SPECIE_ID
INNER JOIN ANML_GENDER
ON ANML_SPECIE.GENDER_ID = ANML_GENDER.GENDER_ID
INNER JOIN ANML_FAMILY
ON ANML_GENDER.FAMILY_ID = ANML_FAMILY.FAMILY_ID
INNER JOIN ANML_SUBORDER
ON ANML_FAMILY.SUBORDER_ID = ANML_SUBORDER.SUBORDER_ID
INNER JOIN ANML_ORDER
ON ANML_SUBORDER.ORDER_ID = ANML_ORDER.ORDER_ID
INNER JOIN ANML_CLASS
ON ANML_ORDER.CLASS_ID = ANML_CLASS.CLASS_ID
WHERE 1=1 AND ANML_SPECIE.SPECIE_COLOR = 'Negro'
;