ALTER TABLE SIGHT
  DROP COLUMN LONGITUDE;
ALTER TABLE SIGHT
  DROP COLUMN LATITUDE;
  
ALTER TABLE DISTRICT
  ADD LONGITUDE NUMBER(20,20) CONSTRAINT DISTRICT_LONGITUDE NOT NULL;
ALTER TABLE DISTRICT
  ADD LATITUDE NUMBER(20,20) CONSTRAINT DISTRICT_LATITUDE NOT NULL;