DROP SEQUENCE SEQ_USER;
CREATE SEQUENCE SEQ_USER
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE
ORDER;
--
--SYSTEM TABLES
--
CREATE TABLE ANML_CLASS(
    CLASS_ID NUMBER(6)              CONSTRAINT CLASS_ID NOT NULL,
    CLASS_NAME VARCHAR2(50)         CONSTRAINT CLASS_NAME NOT NULL
);
CREATE TABLE ANML_ORDER(
    ORDER_ID NUMBER(6)              CONSTRAINT ORDER_ID NOT NULL,
    CLASS_ID NUMBER(6)              CONSTRAINT ORDER_CLASS NOT NULL,
    ORDER_NAME VARCHAR2(50)         CONSTRAINT ORDER_NAME NOT NULL
);
CREATE TABLE ANML_SUBORDER(
    SUBORDER_ID NUMBER(6)           CONSTRAINT SUBORDER_ID NOT NULL,
    ORDER_ID NUMBER(6)              CONSTRAINT SUBORDER_ORDER NOT NULL,
    SUBORDER_NAME VARCHAR2(50)      CONSTRAINT SUBORDER_NAME NOT NULL
);
CREATE TABLE ANML_FAMILY(
    FAMILY_ID NUMBER(6)             CONSTRAINT FAMILY_ID NOT NULL,
    SUBORDER_ID NUMBER(6)           CONSTRAINT FAMILY_SUBORDER NOT NULL,
    FAMILY_NAME VARCHAR2(50)        CONSTRAINT FAMILY_NAME NOT NULL
);
CREATE TABLE ANML_GENDER(
    GENDER_ID NUMBER(6)             CONSTRAINT GENDER_ID NOT NULL,
    FAMILY_ID NUMBER(6)             CONSTRAINT GENDER_FAMILY NOT NULL,
    GENDER_NAME VARCHAR2(50)        CONSTRAINT GENDER_NAME NOT NULL
);
CREATE TABLE ANML_SPECIE(
    SPECIE_ID NUMBER(6)             CONSTRAINT SPECIE_ID NOT NULL,
    GENDER_ID NUMBER(6)             CONSTRAINT SPECIE_GENDER NOT NULL,
    SPECIE_NAME VARCHAR2(50)        CONSTRAINT SPECIE_NAME NOT NULL,
    ENGLISH_NAME VARCHAR2(50)       CONSTRAINT SPECIE_EN_NAME NOT NULL,
    SPANISH_NAME VARCHAR2(50)       CONSTRAINT SPECIE_SP_NAME NOT NULL,
    SCIENTIFIC_NAME VARCHAR2(50)    CONSTRAINT SPECIE_SCNAME NOT NULL,
    SPECIE_COLOR VARCHAR2(50)       CONSTRAINT SPECIE_COLOR NOT NULL,
    SPECIE_SIZE VARCHAR2(50)        CONSTRAINT SPECIE_SIZE NOT NULL,
    DANGER_OF_EXTINCTION NUMBER(1)    CONSTRAINT SPECIE_EXTINCTION NOT NULL
);
CREATE TABLE SIGHT(
    SIGHT_ID NUMBER(6)              CONSTRAINT SIGHT_ID NOT NULL,
    USER_ID NUMBER(6)               CONSTRAINT SIGHT_USER_ID NOT NULL,
    SPECIE_ID NUMBER(6)             CONSTRAINT SIGHT_SPECIE NOT NULL,
    DISTRICT_ID NUMBER(6)           CONSTRAINT SIGHT_DISTRICT NOT NULL,
    LONGITUDE NUMBER(20,20)         CONSTRAINT SIGHT_LONGITUDE NOT NULL,
    LATITUDE NUMBER(20,20)          CONSTRAINT SIGHT_LATITUDE NOT NULL
);
CREATE TABLE IMAGE(
    IMAGE_ID NUMBER(6)              CONSTRAINT IMAGE_ID NOT NULL,
    SIGHT_ID NUMBER(6)              CONSTRAINT IMAGE_SIGHT_ID NOT NULL,
    IMAGE_URL VARCHAR2(100)         CONSTRAINT IMAGE_URL NOT NULL
);
CREATE TABLE SYSTEM_USER(
    USER_ID NUMBER(6)               CONSTRAINT USER_ID NOT NULL,
    USER_NICKNAME VARCHAR2(50)      CONSTRAINT USER_NICKNAME NOT NULL,
    USER_FIRSTNAME VARCHAR2(50)     CONSTRAINT USER_FIRSTNAME NOT NULL,
    USER_LASTNAME VARCHAR2(50)      CONSTRAINT USER_LASTNAME NOT NULL,
    USER_EMAIL VARCHAR2(50)         CONSTRAINT USER_EMAIL NOT NULL,
    USER_PASSWORD VARCHAR2(100)     CONSTRAINT USER_PASSWORD NOT NULL,
    USER_BIRTHDATE DATE             CONSTRAINT USER_BIRTHDATE NOT NULL
);
CREATE TABLE RATEXUSER(
    USER_ID NUMBER(6)               CONSTRAINT RXU_USER NOT NULL,
    SIGHT_ID NUMBER(6)              CONSTRAINT RXU_SIGHT NOT NULL,
    CALIFICATION NUMBER(1)          CONSTRAINT RXU_CALIFICATION NOT NULL
);
CREATE TABLE BINNACLE(
    BINNACLE_ID NUMBER(6)           CONSTRAINT BINNACLE_ID NOT NULL,
    USER_ID NUMBER(6)               CONSTRAINT BINNACLE_USER NOT NULL,
    OLD_PASSWORD VARCHAR2(100)      CONSTRAINT BINNACLE_OLDPASS NOT NULL,
    CURRENT_PASSWORD VARCHAR2(100)  CONSTRAINT BINNACLE_CURPASS NOT NULL,
    MODIFICATION_DATE DATE          CONSTRAINT BINNACLE_DATE NOT NULL
);
CREATE TABLE ORNITHOLOGIST(
    USER_ID NUMBER(6)               CONSTRAINT ORNIT_USER NOT NULL,
    UNIVERSITY VARCHAR2(50)         CONSTRAINT ORNIT_UNIVERSITY NOT NULL,
    GRADUATION_DATE DATE            CONSTRAINT ORNIT_GRADUATION NOT NULL
);
CREATE TABLE AMATEUR(
    USER_ID NUMBER(6)               CONSTRAINT AMATEUR_USER NOT NULL,
    PROFESION VARCHAR(50)           CONSTRAINT AMATEUR_PROFESION NOT NULL
);
CREATE TABLE DISTRICT(
    DISTRICT_ID NUMBER(6)           CONSTRAINT DISTRICT_ID NOT NULL,
    CANTON_ID NUMBER(6)             CONSTRAINT DISTRICT_CANTON NOT NULL,
    DISTRICT_NAME VARCHAR2(50)      CONSTRAINT DISTRICT_NAME NOT NULL
);
CREATE TABLE CANTON(
    CANTON_ID NUMBER(6)             CONSTRAINT CANTON_ID NOT NULL,
    PROVINCE_ID NUMBER(6)           CONSTRAINT CANTON_PROVINCE NOT NULL,
    CANTON_NAME VARCHAR2(50)        CONSTRAINT CANTON_NAME NOT NULL
);
CREATE TABLE PROVINCE(
    PROVINCE_ID NUMBER(6)           CONSTRAINT PROVINCE_ID NOT NULL,
    COUNTRY_ID NUMBER(6)            CONSTRAINT PROVINCE_COUNTRY NOT NULL,
    PROVINCE_NAME VARCHAR2(50)      CONSTRAINT PROVINCE_NAME NOT NULL
);
CREATE TABLE COUNTRY(
    COUNTRY_ID NUMBER(6)            CONSTRAINT COUNTRY_ID NOT NULL,
    CONTINENT_ID NUMBER(6)          CONSTRAINT COUNTRY_CONTINENT NOT NULL,
    COUNTRY_NAME VARCHAR2(50)       CONSTRAINT COUNTRY_NAME NOT NULL
);
CREATE TABLE CONTINENT(
    CONTINENT_ID NUMBER(6)          CONSTRAINT CONTINENT_ID NOT NULL,
    CONTINENT_NAME VARCHAR2(50)     CONSTRAINT CONTINENT_NAME NOT NULL
);
CREATE TABLE SYSTEM_PARAMETERS(
    P_ID NUMBER(6)                  CONSTRAINT SP_ID NOT NULL,
    P_NAME VARCHAR2(50)             CONSTRAINT SP_NAME NOT NULL,
    P_VALUE VARCHAR2(50)            CONSTRAINT SP_VALUE NOT NULL,
    P_DESCRIPTION VARCHAR2(100)     CONSTRAINT SP_DESCRIPTION NOT NULL
);
CREATE TABLE ACTION_HISTORY(
    ACTION_ID NUMBER(6)                         CONSTRAINT ACTION_ID NOT NULL,
    ACTION_NAME VARCHAR2(10)          CONSTRAINT ACTION_NAME NOT NULL,
    TABLE_NAME VARCHAR2(50)           CONSTRAINT TABLE_NAME NOT NULL,
    USER_NAME VARCHAR2(50)            CONSTRAINT USER_NAME NOT NULL,
    ACTION_DATE DATE                             CONSTRAINT ACTION_DATE NOT NULL
);
